FROM nginx:alpine

# Usuwamy domyślną konfigurację
RUN rm /etc/nginx/conf.d/default.conf

# Kopiujemy naszą konfigurację
COPY default.conf /etc/nginx/conf.d/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
